application:
  async-api:
    enabled: true

  datasource-provider:
    enable-caching: true
    default: EXCHANGE_RATE_HOST # DataSourceClientType

    free-currency-api:
      api-key: SdzEzQLNDwnz6mk9WzQIBVrwrIyimchw4bNAe23b

server:
  port: 8080

logging.level.com.betvictor.exchangerate.challenge.app.common: DEBUG

queue.name: exchange-operation-request